In [11]:
# !pip install selenium

In [1]:
from selenium import webdriver
import time
import pandas as pd

In [52]:
url = 'https://www.linkedin.com/jobs/search?keywords=DWDM&location=worldwide&geoId=&trk=public_jobs_jobs-search-bar_search-submit&position=1&pageNum=0'

wd = webdriver.Chrome(executable_path='C:\Windows\chromedriver.exe')
wd.get(url)

In [53]:
# Extract the number of results for search
no_of_jobs_path = '/html/body/div[1]/div/main/div/h1/span[1]'
no_of_jobs = int(wd.find_element_by_xpath(no_of_jobs_path).get_attribute('innerText'))
no_of_jobs

1000

In [54]:
#Scroll down the webpage to display all jobs in query
i = 1
while i <= int(no_of_jobs/25)+1:
    print(i,end="")  #to check kernel is working
    wd.execute_script('window.scrollTo(0, document.body.scrollHeight);')
    i = i + 1
    try:
        wd.find_element_by_xpath('/html/body/div[1]/div/main/section[2]/button').click()
        time.sleep(5)
    except:
        pass
        time.sleep(5)

234567891011121314151617181920212223242526272829303132333435363738394041

In [55]:
# Obtain a list of jobs found in search
job_lists = wd.find_element_by_class_name('jobs-search__results-list')
jobs = job_lists.find_elements_by_tag_name('li') # return a list

In [57]:
# We scrap webpage to obtain data
job_id= []
job_title = []
company_name = []
location = []
date = []
job_link = []
i = 1
for job in jobs:
    print(i,end="")  #To check kernel is working
    job_id0 = i
    job_id.append(job_id0)

    job_title0 = job.find_element_by_css_selector('h3').get_attribute('innerText')
    job_title.append(job_title0)

    company_name0 = job.find_element_by_css_selector('h4').get_attribute('innerText')
    company_name.append(company_name0)

    location0 = job.find_element_by_css_selector('[class="job-search-card__location"]').get_attribute('innerText')
    location.append(location0)
    
    date0 = job.find_element_by_css_selector('div>div>time').get_attribute('datetime')
    date.append(date0)

    job_link0 = job.find_element_by_css_selector('a').get_attribute('href')
    job_link.append(job_link0)
    
    i = i+1

123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100101102103104105106107108109110111112113114115116117118119120121122123124125126127128129130131132133134135136137138139140141142143144145146147148149150151152153154155156157158159160161162163164165166167168169170171172173174175176177178179180181182183184185186187188189190191192193194195196197198199200201202203204205206207208209210211212213214215216217218219220221222223224225226227228229230231232233234235236237238239240241242243244245246247248249250251252253254255256257258259260261262263264265266267268269270271272273274275276277278279280281282283284285286287288289290291292293294295296297298299300301302303304305306307308309310311312313314315316317318319320321322323324325326327328329330331332333334335336337338339340341342343344345346347348349350351352353354355356357358359360361362363364365366367368369370371372373374375376377378379380381382383384385386387388389390391392393394395396397398399400401402403404405406407408409410411412413414415416417418419420421422423424425426427428429430431432433434435436437438439440441442443444445446447448449450451452453454455456457458459460461462463464465466467468469470471472473474475476477478479480481482483484485486487488489490491492493494495496497498499500501502503504505506507508509510511512513514515516517518519520521522523524525526527528529530531532533534535536537538539540541542543544545546547548549550551552553554555556557558559560561562563564565566567568569570571572573574575576577578579580581582583584585586587588589590591592593594595596597598599600601602603604605606607608609610611612613614615616617618619620621622623624625626627628629630631632633634635636637638639640641642643644645646647648649650651652653654655656657658659660661662663664665666667668669670671672673674675676677678679680681682683684685686687688689690691692693694695696697698699700701702703704705706707708709710711712713714715716717718719720721722723724725726727728729730731732733734735736737738739740741742743744745746747748749750751752753754755756757758759760761762763764765766767768769770771772773774775776777778779780781782783784785786787788789790791792793794795796797798799800801802803804805806807808809810811812813814815816817818819820821822823824825826827828829830831832833834835836837838839840841842843844845846847848849850851852853854855856857858859860861862863864865866867868869870871872873874875876877878879880881882883884885886887888889890891892893894895896897898899900901902903904905906907908909910911912913914915916917918919920921922923924925926927928929930931932933934935936937938939940941942943944945946947948949950951952953954955956957958959960961962963964965966967968969970971972973974975976977978979980981982983984985986987988989990991992993994995996997998999

In [64]:
jd = []
seniority = []

i=1
for item in range(len(jobs)):
    print(i,end='')
    try:
        job_click_path = f'/html/body/div[1]/div/main/section[2]/ul/li[{item+1}]/div'
        job_click = job.find_element_by_xpath(job_click_path).click()
        time.sleep(5)
    except:
        job_click_path = f'/html/body/div[1]/div/main/section[2]/ul/li[{item+1}]/a/div[2]/h3'
        job_click = job.find_element_by_xpath(job_click_path).click()
        time.sleep(5)
 
    try:
        jd_path = '/html/body/div[1]/div/section/div[2]/section[2]'
        jd0 = job.find_element_by_xpath(jd_path).get_attribute('innerText')
        jd.append(jd0)
    except:
        jd.append('N/A')
        continue

    try:
        seniority_path = '/html/body/div[1]/div/section/div[2]/section[2]/ul/li[1]/span'
        seniority0 = job.find_element_by_xpath(seniority_path).get_attribute('innerText')
        seniority.append(seniority0)
    except:
        seniority.append('N/A')
        continue
        
    i = i+1

12345678910111213141516171819202122232425262728293031323334353637383940414242434445464748494950515252535455565758596061626364656667686969697071727374757677787980818283848586878889899091929394949596979899100101102103104105106107108109110111112113113114115116117117118119120121122123124125126127128129130131132132133134135136137137138139140141141142142143144145146147148149149150151152153154155156157158159160161162163164165166167168169170170171171172173174175176177178179180180181182183184185186187188189190191192193194195196197198199199200201202202203204205205206207208209210211212213214215215216217218219220220221222223224225226227228229230231232233234235236237238239240241242243244245245246247248249250251252253254255256257258259260261262263263264265266267268269270270271272273274275276277278279280281282283284285286287288289290291292293294295296297298299300301302303304305306306307308309310311312313314315316317318319320321322323324325326327328329330331332333334335336336337337337338339340341341342343344345346347348349350351352353354355356357358359360361362363364365366367368369370371372373374375376377378379380381382382383384385386387387387387388388389390391392393393394395395396396397398399400400401402403404405406407408409410411411412413414415416417417418418419420421422423423423424425426427428429430431432433434434435436437438439440441442443444445446446447448449450451452453454455455456457458459460461461461461462463464465466467468469470471472473474474474475476477478479480481482483484485486487487488489490491492493494495496497497497497498499500501502503504505506507508509510511512513513513513514515516517518519520521522523524525526527528529530531532533534535536537537538539540540541541542543544545546547548549550551552553554555555555556557558559560561561561562562562563564565566567568569570571572573573574575576577577578579580581582583584585586587588589590591592593594595596597598599600601602603604605606607608609610611612612613614615616617618619620621622623624625626627628628628629630631632633634635636637638638639640641642643643643644644645646647648649650651652653654655656657657658659660661662663664665666667668669669670671672673674675676677678679680681682683684685686687688689690691692693694695696697698699700701701702702703704705706707708709710711712713713713714715716717718719720721722723724725726727728729730731732733734735736737738739740741742743743744745745746747748749750751752753754755756757758759760761762763764764765766767768769770770771772773774775776777778779780780780780781781782783784785785786787788789790791792793794794794795796796797798798799800801802803804804805806807808809810811812813814815816817818819820821822823824824825826827828829830831832833834835836837838839840841842843844845846847847848849850851852853853853853854855856857858859860861862863864865865866867868869870871872872872873874875876877878879880881882883884885886887888889890890890891892

In [65]:
#Check all vector have the same lenggh
print(len(date),len(company_name),len(job_title),len(location),len(jd),len(seniority),len(job_link))

999 999 999 999 999 999 999

In [66]:
job_data = pd.DataFrame({'ID': job_id,
'Date': date,
'Company': company_name,
'Title': job_title,
'Location': location,
'Description': jd,
'Level': seniority,
#'Type': emp_type,
#'Function': job_func,
#'Industry': industries,
'Link': job_link
})
# cleaning description column
job_data['Description'] = job_data['Description'].str.replace('\n',' ')

In [49]:
job_data

,ID,Date,Company,Title,Location,Description,Level,Link
0,1,2021-09-13,Facebook,Connectivity Technologies and Ecosystems Manag...,"Londres, Inglaterra, Reino Unido",Facebook's mission is to give people the power...,No corresponde,https://uk.linkedin.com/jobs/view/connectivity...
1,2,2021-09-12,OQ,"IC, Telecom Engineer (Information & Digital So...","Sohar, Al-Bāţinah, Omán",Key Responsibilities Operate Telecommunica...,Intermedio,https://om.linkedin.com/jobs/view/ic-telecom-e...
2,3,2021-09-13,Robi Axiata Limited,"Specialist, Optical Transport Planning","Dacca, Daca, Bangladesh",Job Purpose To plan & design optical network ...,Sin experiencia,https://bd.linkedin.com/jobs/view/specialist-o...
3,4,2021-09-13,NCR Corporation,Project Manager,Calcuta y alrededores,About NCR NCR Corporation (NYSE: NCR) is a le...,Sin experiencia,https://in.linkedin.com/jobs/view/project-mana...
4,5,2021-09-13,ISR Recruitment,Network Development Engineer,"Exeter, Inglaterra, Reino Unido",Enviar mensaje directo al anunciante de ISR Re...,No corresponde,https://uk.linkedin.com/jobs/view/network-deve...
5,6,2021-09-13,Capgemini Engineering,Technical Leader,"Bengaluru, Karnataka, India","Skills Optical OTN, DWDM, ROADM and Network Pl...",Algo de responsabilidad,https://in.linkedin.com/jobs/view/technical-le...
6,7,2021-09-13,AFL,Network Design Engineer,Los Ángeles y alrededores,AFL provides industry-leading fiber optic prod...,Sin experiencia,https://www.linkedin.com/jobs/view/network-des...
7,8,2021-09-13,Accenture,Fiber/Backhaul Consultant,"Edimburgo, Escocia, Reino Unido",Role: Fiber / Backhaul – Consultant Location:...,Intermedio,https://uk.linkedin.com/jobs/view/fiber-backha...
8,9,2021-09-13,Accenture,Fiber/Backhaul Consultant,"Londres, Inglaterra, Reino Unido",Role: Fiber / Backhaul – Consultant Location:...,Intermedio,https://uk.linkedin.com/jobs/view/fiber-backha...
9,10,2021-09-12,Apt,Network Operations Center Engineer,"Ridgeland, Mississippi, Estados Unidos",Our telecommunications client is looking to br...,Intermedio,https://www.linkedin.com/jobs/view/network-ope...
10,11,2021-09-13,Accenture,Fiber/Backhaul Consultant,"Mánchester, Inglaterra, Reino Unido",Role: Fiber / Backhaul – Consultant Location:...,Intermedio,https://uk.linkedin.com/jobs/view/fiber-backha...
11,12,2021-09-13,Tesco,SENIOR SYSTEM ENGINEER - NETWORKS,"Praga, Praga, Chequia",How Is Working In The It Team Special The gro...,Algo de responsabilidad,https://cz.linkedin.com/jobs/view/senior-syste...
12,13,2021-09-13,Bouygues Telecom,Ingénieur Réseau H/F,"Le Tech, Occitània, Francia",Garante de la qualité de service délivrée à no...,Sin experiencia,https://fr.linkedin.com/jobs/view/ing%C3%A9nie...
13,14,2021-09-13,NYC Department of Information Technology & Tel...,Senior Network Support Engineer,"Brooklyn, Nueva York, Estados Unidos",NYC Department of Information Technology & Tel...,N/A,https://www.linkedin.com/jobs/view/senior-netw...
14,15,2021-09-13,Elia,Datacom Field Operator.,"Lendelede, Flandes, Bélgica",Description De Fonction L’employé(e) Datacom ...,Sin experiencia,https://be.linkedin.com/jobs/view/datacom-fiel...
15,16,2021-09-13,Genpact,Consultant- Cisco Data Ops,"Pudong, Shanghái, China",Enviar mensaje directo al anunciante de Genpac...,Intermedio,https://cn.linkedin.com/jobs/view/consultant-c...
16,17,2021-09-13,Accenture,Service Capacity Provisioner,"Dublín, Dublín, Irlanda",Effectively and efficiently manage a queue o...,Sin experiencia,https://ie.linkedin.com/jobs/view/service-capa...
17,18,2021-09-13,Booking.com,Senior Network Engineer,"Manchester, Inglaterra, Reino Unido","Who are we? At Booking.com, we make it easier...",Algo de responsabilidad,https://uk.linkedin.com/jobs/view/senior-netwo...
18,19,2021-09-13,Genpact,Consultant- Cisco Data Ops,"Pudong, Shanghái, China",Enviar mensaje directo al anunciante de Genpac...,Intermedio,https://cn.linkedin.com/jobs/view/consultant-c...
19,20,2021-09-12,BTC Recruitment Malaysia - Executive Search Re...,Network Engineer (MNC IT Service Provider),"Kuala Selangor, Selangor, Malasia",Open Position: Network Engineer (MNC IT Servic...,Intermedio,https://my.linkedin.com/jobs/view/network-engi...
20,21,2021-09-12,Equinix EMEA,EMEA NOC Engineer III,"Varsovia, Mazovia, Polonia",Equinix is the world’s digital infrastructure ...,No corresponde,https://pl.linkedin.com/jobs/view/emea-noc-eng...
21,22,2021-09-13,Finanz Informatik Technologie Service,IT-Security-/Netzwerkexperte (m/w/d),"Haar, Baviera, Alemania",Enviar mensaje directo al anunciante de Finanz...,Algo de responsabilidad,https://de.linkedin.com/jobs/view/it-security-...
22,23,2021-09-12,Netcracker Technology,"Senior Business Analyst, OSS","Denver, Colorado, Estados Unidos",Rango de sueldo estimado El sueldo real puede...,N/A,https://www.linkedin.com/jobs/view/senior-busi...
23,24,2021-09-13,West Elm,"Visual Sales Merchandiser, Part-Time, West Elm...","Denver, Colorado, Estados Unidos",Job Description You’re excited about this PAR...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/visual-sale...
24,25,2021-09-13,West Elm,"Shipper-Receiver West Elm Outlet Vacaville, CA","Vacaville, California, Estados Unidos",Job Description **** About the Team **** Hir...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/shipper-rec...
25,26,2021-09-13,"Williams-Sonoma, Inc.",Stock Assoc,"Phoenix, Arizona, Estados Unidos",Job Description **** About the Team **** Hir...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/stock-assoc...
26,27,2021-09-12,"Williams-Sonoma, Inc.",Stock Assoc,"Dedham, Massachusetts, Estados Unidos",Job Description **** About the Team **** Hir...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/stock-assoc...
27,28,2021-09-13,"Williams-Sonoma, Inc.",Sales Assoc,"Birch Run, Michigan, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
28,29,2021-09-12,"Williams-Sonoma, Inc.",Sales Assoc,"Métairie, Luisiana, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
29,30,2021-09-12,"Williams-Sonoma, Inc.",Sales Assoc,"Bethesda, Maryland, Estados Unidos",Job Description ***About the Team**** You ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
30,31,2021-09-13,West Elm,"Sales Assoc, Part Time, Armory, West Elm","Rochester, Nueva York, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
31,32,2021-09-13,West Elm,Part-Time | Stock Associate | Carytown | west ...,"Richmond, Virginia, Estados Unidos",Job Description **** About the Team **** Hir...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/part-time-s...
32,33,2021-09-12,Pottery Barn,"Assoc Store Mgr, Full-time, Princeton Marketfa...","Princeton, Nueva Jersey, Estados Unidos",Job Description **** About the Team **** Hir...,Intermedio,https://www.linkedin.com/jobs/view/assoc-store...
33,34,2021-09-13,"Williams-Sonoma, Inc.",FT Stock Associate,"Riverhead, Nueva York, Estados Unidos",Job Description **** About the Team **** Hir...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/ft-stock-as...
34,35,2021-09-13,West Elm,Seasonal Sales Associate | Hyde Park | west el...,"Tampa, Florida, Estados Unidos",About The Role Job Description As a Sales As...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/seasonal-sa...
35,36,2021-09-13,"Williams-Sonoma, Inc.",Full-Time Sales Associate,"Lancaster, Pennsylvania, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/full-time-s...
36,37,2021-09-13,West Elm,Seasonal | Sales Associate | Streets at Southp...,"Durham, Carolina del Norte, Estados Unidos",About The Role Job Description As a Sales As...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/seasonal-sa...
37,38,2021-09-13,"Williams-Sonoma, Inc.",Seasonal Sales Assoc,"Savannah, Georgia, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/seasonal-sa...
38,39,2021-09-13,"Williams-Sonoma, Inc.","Sales Assoc, part-time, Chelsea-Williams Sonoma","Nueva York, Nueva York, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
39,40,2021-09-13,"Williams-Sonoma, Inc.","Sales Assoc, Part-Time, Legacy Village - Willi...","Mobile, Alabama, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
40,41,2021-09-13,"Williams-Sonoma, Inc.","Sales Associate, Part-Time, Central Park - Wil...","Austin, Texas, Estados Unidos",Job Description * * ** About the Team *** * ...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
41,42,2021-09-12,Pottery Barn,"Sales Associate, Pottery Barn Outlet, Gaffney SC","Gaffney, Carolina del Sur, Estados Unidos",Job Description ***About the Team**** Hiring...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/sales-assoc...
42,43,2021-09-13,"Williams-Sonoma, Inc.","Cashier, Part Time, NorthPark Center - William...","Dallas, Texas, Estados Unidos",Job Description **** About the Team **** Our...,Algo de responsabilidad,https://www.linkedin.com/jobs/view/cashier-par...

In [67]:
job_data.to_csv('linkedin_data1000',index=False)

In [80]:
job_data.groupby(['Company']).count().sort_values('Date',ascending=False).head(10)

                           ID  Date  Title  Location  Description  Level  Link
Company
Crown Castle               34    34     34        34           34     34    34
Ciena                      32    32     32        32           32     32    32
Nokia                      25    25     25        25           25     25    25
Microsoft                  24    24     24        24           24     24    24
Spectrum                   24    24     24        24           24     24    24
Lumen Technologies         23    23     23        23           23     23    23
Amazon Web Services (AWS)  22    22     22        22           22     22    22
Zayo Group                 18    18     18        18           18     18    18
BT                         17    17     17        17           17     17    17
Ribbon Communications      15    15     15        15           15     15    15

In [81]:
job_data.groupby(['Location']).count().sort_values('Date',ascending=False).head(10)

,ID,Date,Company,Title,Description,Level,Link
Location,,,,,,,
"Singapur, Singapur",49,49,49,49,49,49,49
"Dublín, Dublín, Irlanda",18,18,18,18,18,18,18
"Seattle, Washington, Estados Unidos",17,17,17,17,17,17,17
"Sydney, Nueva Gales del Sur, Australia",16,16,16,16,16,16,16
"Londres, Inglaterra, Reino Unido",14,14,14,14,14,14,14
"Tokio, Japón",14,14,14,14,14,14,14
"Dallas, Texas, Estados Unidos",14,14,14,14,14,14,14
"Bengaluru, Karnataka, India",13,13,13,13,13,13,13
"Washington, Distrito de Columbia, Estados Unidos",13,13,13,13,13,13,13
"Richardson, Texas, Estados Unidos",12,12,12,12,12,12,12

In [83]:
print(job_data['Date'].min())
print(job_data['Date'].max())

2021-03-01
2021-09-13

In [89]:
job_data.groupby(['Level']).count().sort_values('Date',ascending=False).head(10)

,ID,Date,Company,Title,Location,Description,Link
Level,,,,,,,
Sin experiencia,221,221,221,221,221,221,221
No corresponde,173,173,173,173,173,173,173
Algo de responsabilidad,166,166,166,166,166,166,166
Intermedio,158,158,158,158,158,158,158
N/A,107,107,107,107,107,107,107
\n Sin experiencia\n,39,39,39,39,39,39,39
\n Algo de responsabilidad\n,32,32,32,32,32,32,32
Jornada completa,26,26,26,26,26,26,26
\n Intermedio\n,24,24,24,24,24,24,24
\n No corresponde\n,22,22,22,22,22,22,22